sonar.host.url=http://vnmap_sonarqube:9000
sonar.projectKey=vnm-backend
sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true
sonar.java.binaries=target/classes
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.qualitygate.wait=true
